name: Rust

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: "" # reads from rust-toolchain.toml
    - name: Set up cargo cache
      uses: actions/cache@v3
      continue-on-error: false
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: cargo-lint-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: cargo-lint-
    - name: Fmt
      run: cargo fmt -- --check
    - name: Clippy
      run: cargo clippy

  build:
    needs: lint
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: "" # reads from rust-toolchain.toml
    - name: Set up cargo cache
      uses: actions/cache@v3
      continue-on-error: false
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: cargo-${{ matrix.os }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: cargo-${{ matrix.os }}-
    - name: Test
      run: cargo test
    - name: Build
      run: cargo build
